"""
noise_main.py — DSLM noise robustness experiments (binary classification).

Evaluates DSLM under simulated imaging noise on:
  - Brain Tumor (MRI): Gaussian + Rician noise
  - Tuberculosis (Chest X-ray): Gaussian + Poisson noise

Two scenarios:
  'test_only'  — train on clean encodings, test on noisy encodings
  'train_test' — both train and test use noisy encodings

Noise is applied in image pixel space before ResNet feature extraction.
Pre-computed noisy encodings are loaded from CSV (generated by extract_noisy_features.py),
making repeated experiments fast without redundant image loading or feature extraction.

Logs one row per run (final result only) to: log/noise_dslm_{date}.csv

Log columns:
  dataset, elite_fitness, elite_test_fitness, elite_size, elite_length,
  elite_hidden_layers, brmse, mcc, bce, seed, generation(=2000), timing
  (dataset string encodes: loader_resnetv_size_metric_noisetype_noiselevel_scenario)
"""
import sys, os
_here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_here, '..', '..'))  # repo root
sys.path.insert(0, _here)                             # sibling imports
LOG_DIR = os.path.join(_here, '..', '..', 'log')

import numpy as np
import torch
import datetime
import time
from DSLM import DSLM
from datasets.data_loader_resnet import load_brain_tumor, load_tuberculosis, load_noisy_dataset
from utils.utils import StandardScaler, uniform_random_step_generator
from utils.evaluators import binarized_rmse, binarized_bce, binarized_mcc
from utils.info import get_log_info, base_logger
from population.initializers import initialize_population
from population.selection_algorithms import torunament_selection
from individual.mutation_operators import deflate_mutation, inflate_mutation
from sklearn.model_selection import train_test_split
from torch import nn, optim
from noise_utils import DATASET_NOISE_TYPES, NOISE_LEVELS, NOISE_SCENARIOS

now = datetime.datetime.now()
day = now.strftime("%Y%m%d")

loaders = [load_brain_tumor, load_tuberculosis]
resnet_versions = ['rn18', 'rn34', 'rn50']
metrics = [binarized_rmse(), binarized_bce()]
sizes = [10, 50, 100, 250, 500]
seeds = 30


def _run(seed, loader, resnet_v, metric, size, noise_type, noise_level, noise_scenario):
    dataset_name = loader.__name__.split("load_")[-1]
    dataset = (f"{dataset_name}_{resnet_v}_{size}_{metric.__name__}"
               f"_{noise_type}_{noise_level}_{noise_scenario}")

    # Load clean and noisy encodings (row order identical — same split indices apply)
    X_clean, y = loader(model_type=resnet_v, X_y=True)
    X_noisy, _ = load_noisy_dataset(dataset_name, model_type=resnet_v,
                                    noise_type=noise_type, noise_level=noise_level)

    if hasattr(X_clean, 'numpy'):
        X_clean = X_clean.numpy()
    if hasattr(y, 'numpy'):
        y = y.numpy()

    # Normalize (fit on full clean data so clean and noisy share the same scale)
    scaler  = StandardScaler().fit(X_clean)
    X_clean = scaler.transform(X_clean)
    X_noisy = scaler.transform(X_noisy)

    idx = np.arange(len(y))
    idx_train, idx_test, y_train, y_test = train_test_split(
        idx, y, train_size=size, random_state=seed, stratify=y)

    if noise_scenario == 'test_only':
        X_train = X_clean[idx_train]
        X_test  = X_noisy[idx_test]
    else:  # 'train_test'
        X_train = X_noisy[idx_train]
        X_test  = X_noisy[idx_test]

    X_train_nn, X_val, y_train_nn, y_val = train_test_split(
        X_train, y_train, test_size=0.2, random_state=seed, stratify=y_train)

    X_train, X_test, y_train, y_test, X_train_nn, X_val, y_train_nn, y_val = (
        torch.Tensor(X_train), torch.Tensor(X_test),
        torch.Tensor(y_train).squeeze(), torch.Tensor(y_test).squeeze(),
        torch.Tensor(X_train_nn), torch.Tensor(X_val),
        torch.Tensor(y_train_nn).squeeze(), torch.Tensor(y_val).squeeze()
    )

    start = time.time()
    optimizer = DSLM(
        initializer=initialize_population(
            X_train_nn, y_train_nn,
            maximum_width=128, maximum_depth=6,
            activation_functions=[nn.ReLU()],
            pretrain_part=0.5,
            X_val=X_val, y_val=y_val,
            epochs=100, batch_size=32, learning_rate=0.001,
            criterion=nn.MSELoss(), optimizer=optim.Adam, device='cpu'
        ),
        selector=torunament_selection(2),
        inflate_mutator=inflate_mutation(
            X_train,
            ms_generator=uniform_random_step_generator(0, 0.002),
            X_test=X_test
        ),
        deflate_mutator=deflate_mutation,
        crossover=None,
        p_m=1, p_im=0.3, p_dm=0.7, p_xo=0,
        pop_size=100, seed=seed,
    )
    # log=0 suppresses per-generation logging; we log only the final result below
    optimizer.solve(
        X_train=X_train, y_train=y_train,
        X_test=X_test, y_test=y_test,
        metric=metric, max_depth=None, generations=2000, elitism=True,
        dataset_name=dataset,
        log=0, log_path=None, verbose=0, n_jobs=-1
    )
    end = time.time()

    row = [dataset] + get_log_info(optimizer, log=2) + [seed, 2000, round(end - start, 4)]
    base_logger(path=os.path.join(LOG_DIR, f'noise_dslm_{day}.csv'), row=row)
    return 'done'


if __name__ == '__main__':
    for loader in loaders:
        for resnet_v in resnet_versions:
            for metric in metrics:
                for size in sizes:
                    for noise_type in DATASET_NOISE_TYPES[loader.__name__]:
                        for noise_level in NOISE_LEVELS:
                            for noise_scenario in NOISE_SCENARIOS:
                                for seed in range(seeds):
                                    _run(seed, loader, resnet_v, metric, size,
                                         noise_type, noise_level, noise_scenario)
