"""
noise_fs_baseline.py — Few-shot baseline noise robustness experiments.

Evaluates ProtoNet, MAML, and Transductive Fine-Tuning under simulated
imaging noise. Matching Networks is excluded (commented out in fs_baseline.py).

Noise is applied in image pixel space before ResNet feature extraction.
Pre-computed noisy encodings are loaded from CSV (generated by extract_noisy_features.py),
making repeated experiments fast without redundant image loading or feature extraction.

Datasets:
  - Brain Tumor (MRI): Gaussian + Rician noise
  - Tuberculosis (Chest X-ray): Gaussian + Poisson noise

Two scenarios:
  'test_only'  — train on clean encodings, test on noisy encodings
  'train_test' — both support (train) and query (test) use noisy encodings

Logs to: log/noise_fs_baseline_{date}.csv
Log columns: dataset, seed, train_size, test_size, n_classes,
             protonet_train_mcc, protonet_test_mcc,
             maml_train_mcc, maml_test_mcc,
             transductive_train_mcc, transductive_test_mcc,
             noise_type, noise_level, noise_scenario
"""
import sys, os
_here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_here, '..', '..'))
sys.path.insert(0, _here)
LOG_DIR = os.path.join(_here, '..', '..', 'log')

import numpy as np
import torch
import datetime
from datasets.data_loader_resnet import load_brain_tumor, load_tuberculosis, load_noisy_dataset
from utils.utils import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import matthews_corrcoef
from fs_baseline import protonet, maml, transductive_finetune, log_results
from noise_utils import DATASET_NOISE_TYPES, NOISE_LEVELS, NOISE_SCENARIOS

now = datetime.datetime.now()
day = now.strftime("%Y%m%d")

loaders = [load_brain_tumor, load_tuberculosis]
resnet_versions = ['rn18', 'rn34', 'rn50']
sizes = [10, 50, 100, 250, 500]
seeds = 5


def _run(seed, loader, resnet_v, size, noise_type, noise_level, noise_scenario):
    dataset_name = loader.__name__.split("load_")[-1]
    dataset = f"{dataset_name}_{resnet_v}_{size}"

    # Load clean and noisy encodings (row order identical — same split indices apply)
    X_clean, y = loader(model_type=resnet_v, X_y=True)
    X_noisy, _ = load_noisy_dataset(dataset_name, model_type=resnet_v,
                                    noise_type=noise_type, noise_level=noise_level)

    if hasattr(X_clean, 'numpy'):
        X_clean = X_clean.numpy()
    if hasattr(y, 'numpy'):
        y = y.numpy()

    # Normalize (fit on full clean data)
    scaler  = StandardScaler().fit(X_clean)
    X_clean = scaler.transform(X_clean)
    X_noisy = scaler.transform(X_noisy)

    idx = np.arange(len(y))
    idx_train, idx_test, y_train, y_test = train_test_split(
        idx, y, train_size=size, random_state=seed, stratify=y)

    if noise_scenario == 'test_only':
        X_train = X_clean[idx_train]
        X_test  = X_noisy[idx_test]
    else:  # 'train_test'
        X_train = X_noisy[idx_train]
        X_test  = X_noisy[idx_test]

    X_train = torch.Tensor(X_train)
    X_test  = torch.Tensor(X_test)
    y_train = torch.Tensor(y_train).squeeze()
    y_test  = torch.Tensor(y_test).squeeze()

    n_classes = len(torch.unique(y_train))

    results = {
        'dataset': dataset,
        'seed': seed,
        'train_size': X_train.shape[0],
        'test_size':  X_test.shape[0],
        'n_classes':  n_classes,
    }

    # ProtoNet
    pred_train, pred_test = protonet(X_train, y_train, X_test, y_test, n_classes)
    results['protonet_train_mcc'] = matthews_corrcoef(y_train.numpy(), pred_train.numpy())
    results['protonet_test_mcc']  = matthews_corrcoef(y_test.numpy(),  pred_test.numpy())

    # MAML
    pred_train, pred_test = maml(X_train, y_train, X_test, y_test, n_classes,
                                  inner_lr=0.01, outer_steps=20)
    results['maml_train_mcc'] = matthews_corrcoef(y_train.numpy(), pred_train.numpy())
    results['maml_test_mcc']  = matthews_corrcoef(y_test.numpy(),  pred_test.numpy())

    # Transductive Fine-Tuning
    pred_train, pred_test = transductive_finetune(X_train, y_train, X_test, y_test, n_classes,
                                                   epochs=100, lr=0.001)
    results['transductive_train_mcc'] = matthews_corrcoef(y_train.numpy(), pred_train.numpy())
    results['transductive_test_mcc']  = matthews_corrcoef(y_test.numpy(),  pred_test.numpy())

    results['noise_type']     = noise_type
    results['noise_level']    = noise_level
    results['noise_scenario'] = noise_scenario

    log_results(os.path.join(LOG_DIR, f'noise_fs_baseline_{day}.csv'), results)
    return results


if __name__ == '__main__':
    for loader in loaders:
        for resnet_v in resnet_versions:
            for size in sizes:
                for noise_type in DATASET_NOISE_TYPES[loader.__name__]:
                    for noise_level in NOISE_LEVELS:
                        for noise_scenario in NOISE_SCENARIOS:
                            for seed in range(seeds):
                                _run(seed, loader, resnet_v, size,
                                     noise_type, noise_level, noise_scenario)
