"""
noise_baseline.py — Standard NN baseline noise robustness (binary classification).

Evaluates the fixed-architecture NN baseline under simulated imaging noise.
Uses the same architecture (depth/width) as baseline.py for comparability.

Noise is applied in image pixel space before ResNet feature extraction.
Pre-computed noisy encodings are loaded from CSV (generated by extract_noisy_features.py),
making repeated experiments fast without redundant image loading or feature extraction.

Datasets:
  - Brain Tumor (MRI): Gaussian + Rician noise
  - Tuberculosis (Chest X-ray): Gaussian + Poisson noise

Two scenarios:
  'test_only'  — train on clean encodings, test on noisy encodings
  'train_test' — both train and test use noisy encodings

Logs to: log/noise_baseline_{date}.csv
Log columns: dataset, noise_type, noise_level, noise_scenario,
             brmse, bce, mcc, seed, generation(=2000), timing
"""
import sys, os
_here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_here, '..', '..'))
sys.path.insert(0, _here)
LOG_DIR = os.path.join(_here, '..', '..', 'log')

import numpy as np
import torch
import datetime
import time
from NeuralNetwork.utils import create_network
from NeuralNetwork.NeuralNetwork import NeuralNetwork
from datasets.data_loader_resnet import load_brain_tumor, load_tuberculosis, load_noisy_dataset
from utils.utils import StandardScaler
from utils.evaluators import binarized_mcc, binarized_rmse, binarized_bce
from utils.info import base_logger
from sklearn.model_selection import train_test_split
from torch import nn
from baseline import size as arch_size
from noise_utils import DATASET_NOISE_TYPES, NOISE_LEVELS, NOISE_SCENARIOS

now = datetime.datetime.now()
day = now.strftime("%Y%m%d")

loaders = [load_brain_tumor, load_tuberculosis]
resnet_versions = ['rn18', 'rn34', 'rn50']
sample_sizes = [10, 50, 100, 250, 500]
seeds = 10


def _run(seed, loader, resnet_v, sample_size, noise_type, noise_level, noise_scenario):
    dataset_name = loader.__name__.split("load_")[-1]
    dataset = f"{dataset_name}_{resnet_v}_{sample_size}"

    # Load clean and noisy encodings (row order identical — same split indices apply)
    X_clean, y = loader(model_type=resnet_v, X_y=True)
    X_noisy, _ = load_noisy_dataset(dataset_name, model_type=resnet_v,
                                    noise_type=noise_type, noise_level=noise_level)

    # Convert to numpy if torch.Tensor
    if hasattr(X_clean, 'numpy'):
        X_clean = X_clean.numpy()
    if hasattr(y, 'numpy'):
        y = y.numpy()

    # Normalize (fit on full clean data so clean and noisy share the same scale)
    scaler  = StandardScaler().fit(X_clean)
    X_clean = scaler.transform(X_clean)
    X_noisy = scaler.transform(X_noisy)

    # Match architecture from baseline.py (max of bce/brmse variants)
    key_bce   = f"{dataset}_bce"
    key_brmse = f"{dataset}_brmse"
    depth = max(arch_size['depth'][key_bce], arch_size['depth'][key_brmse])
    width = max(arch_size['width'][key_bce], arch_size['width'][key_brmse])

    # Split indices (applied to both clean and noisy arrays)
    idx = np.arange(len(y))
    idx_train, idx_test, y_train, y_test = train_test_split(
        idx, y, train_size=sample_size, random_state=seed, stratify=y)
    idx_train, idx_val, y_train, y_val = train_test_split(
        idx_train, y_train, test_size=0.2, random_state=seed, stratify=y_train)

    if noise_scenario == 'test_only':
        X_train = X_clean[idx_train]
        X_val   = X_clean[idx_val]
        X_test  = X_noisy[idx_test]
    else:  # 'train_test'
        X_train = X_noisy[idx_train]
        X_val   = X_noisy[idx_val]
        X_test  = X_noisy[idx_test]

    net = NeuralNetwork(create_network(
        X_train.shape[1], width=1, depth=int(width) * int(depth),
        num_outputs=1, output_activation=None
    ))

    X_train = torch.Tensor(X_train)
    X_test  = torch.Tensor(X_test)
    X_val   = torch.Tensor(X_val)
    y_train = torch.Tensor(y_train).long()
    y_test  = torch.Tensor(y_test).long()
    y_val   = torch.Tensor(y_val).long()

    start = time.time()
    net.train_network(X_train, y_train.float(),
                      X_val=X_val, y_val=y_val.float(),
                      X_test=X_test, y_test=y_test.float(),
                      epochs=2000, batch_size=32,
                      criterion=nn.BCEWithLogitsLoss())
    end = time.time()

    y_pred = net.forward(X_test).flatten()

    row = [dataset, noise_type, noise_level, noise_scenario,
           binarized_rmse()(y_test.float(), y_pred),
           binarized_bce()(y_test.float(),  y_pred),
           binarized_mcc()(y_test.float(),  y_pred),
           seed, 2000, round(end - start, 4)]
    base_logger(path=os.path.join(LOG_DIR, f'noise_baseline_{day}.csv'), row=row)
    return 'done'


if __name__ == '__main__':
    for loader in loaders:
        for resnet_v in resnet_versions:
            for sample_size in sample_sizes:
                for noise_type in DATASET_NOISE_TYPES[loader.__name__]:
                    for noise_level in NOISE_LEVELS:
                        for noise_scenario in NOISE_SCENARIOS:
                            for seed in range(seeds):
                                _run(seed, loader, resnet_v, sample_size,
                                     noise_type, noise_level, noise_scenario)
